name: dartboot_clickhouse
description: Clickhouse client for dart.
version: 1.0.0
homepage: https://github.com/dartboot/dartboot_clickhouse

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dependencies:
  dartboot_db: ^1.0.1
  dartboot_util: ^1.0.0
  dartboot_core: ^1.0.10
  dartboot_annotation: ^1.0.0
  build: ^1.2.2
  build_runner: ^1.9.0
  source_gen: ^0.9.4+6
